f = open("samplefile.txt", "w")
f.write("Its easy to learn")
f = open("samplefile.txt", "a")
f.write("\nCreate a simple program")
f.write("\nTry to create a simple program")
f.write("\nTo learn programming")
f = open("samplefile.txt", "r")
f.close()